# Generated by Django 5.2.1 on 2025-05-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
